//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTEMerchant
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImgPath
    {
        public int Item_Id { get; set; }
        public string Path { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
