//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTEMerchant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.CustomerReviews = new HashSet<CustomerReview>();
            this.ImgPaths = new HashSet<ImgPath>();
            this.PurchasedProducts = new HashSet<PurchasedProduct>();
            this.Wishlists = new HashSet<Wishlist>();
        }
    
        public int Item_Id { get; set; }
        public string name { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> original_price { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> bought_date { get; set; }
        public string condition_description { get; set; }
        public Nullable<int> condition { get; set; }
        public string image_path { get; set; }
        public Nullable<bool> sale_status { get; set; }
        public string detail_description { get; set; }
        public int SellerID { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerReview> CustomerReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImgPath> ImgPaths { get; set; }
        public virtual Seller Seller { get; set; }
        public virtual ItemClick ItemClick { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchasedProduct> PurchasedProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wishlist> Wishlists { get; set; }
    }
}
