//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTEMerchant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wishlist
    {
        public int WishlistID { get; set; }
        public int Id_user { get; set; }
        public int Item_Id { get; set; }
        public System.DateTime AddedDate { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual User User { get; set; }
    }
}
